// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jgnlxviifrndhbrmobsg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impnbmx4dmlpZnJuZGhicm1vYnNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3ODM0MjYsImV4cCI6MjA1NjM1OTQyNn0.g_jSuDaCl3D2YehATbUEJvza8mu_Ug-zYGyTlXSpQiE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);